include: package:lints/recommended.yaml

analyzer:
  exclude:
    # ignore vscode .history files
    - .history/**
    - test_data/**
  language:
    strict-casts: true
linter:
  rules:
#    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
#    - always_specify_types
    - avoid_annotating_with_dynamic
#    - avoid_bool_literals_in_conditional_expressions # under review (see #1068)
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
#    - avoid_classes_with_only_static_members
#    - avoid_double_and_int_checks # under review (see #1068)
#    - avoid_field_initializers_in_const_classes # under review (see #1068)
#    - avoid_implementing_value_types
#    - avoid_js_rounded_ints # under review (see #1068)
    - avoid_positional_boolean_parameters
    - avoid_print
#    - avoid_private_typedef_functions # under review (see #1068)
    - avoid_redundant_argument_values
#    - avoid_renaming_method_parameters # under review (see #1068)
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_slow_async_io
#    - avoid_types_on_closure_parameters
#    - avoid_unused_constructor_parameters # under review (see #1068)
#    - avoid_void_async # under review (see #1068)
    - cancel_subscriptions
#    - cascade_invocations
    - cast_nullable_to_non_nullable
#    - combinators_ordering
#    - close_sinks # https://github.com/dart-lang/linter/issues/268
    - comment_references
    - dangling_library_doc_comments
    - directives_ordering
    - discarded_futures
    - join_return_with_assignment
#    - lines_longer_than_80_chars # under review (see #1068)
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - noop_primitive_operations
#    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
#    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
#    - prefer_const_declarations # under review (see #1068)
#    - prefer_const_literals_to_create_immutables # under review (see #1068)
    - prefer_constructors_over_static_methods
    - prefer_expression_function_bodies
#    - prefer_final_locals
    - prefer_foreach
#    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_relative_imports
    - prefer_single_quotes
#    - public_member_api_docs
#    - sort_constructors_first
    - sort_pub_dependencies
#    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
#    - type_annotate_public_apis
    - unawaited_futures # pedantic
    - unnecessary_breaks
    - unnecessary_final
    - unnecessary_lambdas
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_if_null_to_convert_nulls_to_bools
    - use_late_for_private_fields_and_variables
    - use_setters_to_change_properties
    - use_string_buffers
    - use_super_parameters
    - use_to_and_as_if_applicable
