name: linter
version: 1.30.1

description: >-
  Discontinued. This package is not intended to be used directly.
homepage: https://dart.dev/tools/linter-rules
repository: https://github.com/dart-lang/linter

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  args: ^2.1.0
  collection: ^1.15.0
  http: ^0.13.0
  meta: ^1.3.0
  path: ^1.8.0
  source_span: ^1.8.0
  yaml: ^3.0.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  cli_util: ^0.3.0
  github: ^9.0.0
  grinder: ^0.9.0
  lints: ^2.0.0
  markdown: ^6.0.0
  matcher: ^0.12.10
  pub_semver: ^2.0.0
  test: ^1.16.1
  test_reflective_loader: ^0.2.0
