blank_issues_enabled: true
contact_links:
  - name: Dart team recommended lints
    url: https://github.com/dart-lang/lints/issues/new/choose
    about: Request a lint for inclusion, exclusion or otherwise discuss Dart team recommended lints.
