name: "issue labeler"

on:
  issues:
    types: [opened, edited]

permissions: read-all

jobs:
  triage:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@98b5412841f6c4b0b3d9c29d53c13fad16bd7de2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
          include-title: 1
