name: "labeler"

on:
  - pull_request_target

permissions: read-all

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
