name: link check

on:
  - pull_request_target

permissions: read-all

jobs:
  check-links:
    name: link check
    runs-on: ubuntu-latest
    steps:
      - name: link check
        uses: filiph/linkcheck@f2c15a0be0d9c83def5df3edcc0f2d6582845f2d
        with:
          arguments: -e https://dart-lang.github.io/linter/lints/index.html
